version: "3.1"

services:
  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: devpleno
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: devpleno
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
